mayastorImagesTag: latest
mayastorImagePullPolicy: Always
mayastorLogLevel: info
mayastorCpuCount: "1"
mayastorHugePagesGiB: "1"
mayastorImagesRegistry: ""
mayastorPools: []

# This option is intended for development yamls and motivated by the problem of
# moac that does not update status of msp resource in some cases. Feel free to
# remove when no longer needed.
moacDebug: false
moac: false

csi:
  nvme:
    # nvme_core module io timeout in seconds
    io_timeout: "30"
    io_timeout_enabled: true

nats:
  image: nats
  tag: 2.7.2-alpine3.15

  reloader:
    image: natsio/nats-server-config-reloader
    tag: 0.6.2

  exporter:
    enabled: false
    image: natsio/prometheus-nats-exporter
    tag: 0.9.1

  replicas: 3

  logging:
    debug: false
    trace: false

etcd:
  auth:
    rbac:
      enabled: false

  ## Number of replicas
  ##
  replicaCount: 3
  ## Kubernetes Cluster Domain
  ##
  clusterDomain: cluster.local
  ## TLS authentication for client-to-server communications
  ## ref: https://etcd.io/docs/current/op-guide/security/
  ##
  client:
    secureTransport: false
  ## TLS authentication for server-to-server communications
  ## ref: https://etcd.io/docs/current/op-guide/security/
  ##
  peer:
    secureTransport: false
  ## Enable persistence using Persistent Volume Claims
  ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
  ##
  persistence:
    ## If true, use a Persistent Volume Claim. If false, use emptyDir.
    ##
    enabled: true
    ## Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    storageClass: "manual"
    ## Persistent Volume size
    ##
    size: 2Gi

  ## Init containers parameters:
  ## volumePermissions: Change the owner and group of the persistent volume mountpoint to runAsUser:fsGroup values from the securityContext section.
  ##
  volumePermissions:
    enabled: true

  ## Set to true if you would like to see extra information on logs
  ##
  debug: false

  ## Pod anti-affinity preset
  ## Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
  ## Allowed values: soft, hard
  ##
  podAntiAffinityPreset: "hard"
