[package]
name = "io-engine-bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
uuid = { workspace = true, features = ["v4"] }
io-engine = { path = "../io-engine" }
io-engine-tests = { path = "../io-engine-tests" }
criterion = { version = "0.5.1", features = ["async_tokio"] }

[[bench]]
name = "nexus"
path = "src/nexus.rs"
harness = false
