git:
  depth: false
  submodules: false

dist: bionic
cache:
  cargo: true
  directories:
    - $HOME/.cargo
    - $TRAVIS_BUILD_DIR/target
    - csi/moac/node_modules
    - mayastor-test/node_modules

before_script:
  - nix-env -iA cachix -f https://cachix.org/api/v1/install
  - cachix use mayastor
  - export NIX_PATH="$NIX_PATH:nixpkgs-overlays=/home/travis/build/openebs/MayaStor/nix"
  - git submodule update --init
  - sudo modprobe nbd
  - sudo modprobe iscsi_tcp
  - sudo modprobe xfs
  - sudo sysctl -w vm.nr_hugepages=512
  - source $HOME/.nvm/nvm.sh
  - nvm install 10
  - curl -sSf https://build.travis-ci.org/files/rustup-init.sh | sh -s -- --default-toolchain=nightly-2019-08-15 -y
language: nix

script:
  - glibcLocales=$(nix-build --no-out-link "<nixpkgs>" -A glibcLocales)
  - echo $glibcLocales
  - export LOCALE_ARCHIVE_2_27="${glibcLocales}/lib/locale/locale-archive"
  - nix-shell --run ./test.sh
