# must pass befor merge in master
status = ["Build", "Clippy"]
# must pass before staging
pr_status = ["Clippy"]
# dont want merge commits do we?
use_squash_merge = true
required_approvals = 2
# add issue key behind this and it wont show in the commit
cut_body_after = "!!!"
