[package]
name = "libnvme-rs"
description = "Rust bindings for libnvme"
version = "0.1.0"
edition = "2018"
build = "build.rs"
license = "Apache-2.0"
authors = [
    "Jonathan Teh <jonathan.teh@mayadata.io>",
    "Jeffry Molanus <jeffry.molanus@gmail.com>",
]

[build-dependencies]
bindgen = "0.70.1"
cc = "1.1.31"

[dependencies]
glob = "0.3.1"
libc = "0.2"
snafu = "0.8.5"
url = "2.5.4"

[dependencies.mio]
package = "mio"
features = ["os-ext"]
version = "1.0"

[dependencies.udev]
features = ["hwdb", "mio"]
version = "^0.9.1"

[dependencies.uuid]
features = ["v4"]
version = "1.11.0"
