[package]
name = "libnvme-rs"
description = "Rust bindings for libnvme"
version = "0.1.0"
edition = "2018"
build = "build.rs"
license = "Apache-2.0"
authors = [
    "Jonathan Teh <jonathan.teh@mayadata.io>",
    "Jeffry Molanus <jeffry.molanus@gmail.com>",
]

[build-dependencies]
bindgen = { workspace = true }
cc = { workspace = true }

[dependencies]
glob = { workspace = true }
libc = { workspace = true }
snafu = { workspace = true }
url = { workspace = true }

[dependencies.mio]
package = "mio"
features = ["os-ext"]
version = "1.0"

[dependencies.udev]
features = ["hwdb", "mio"]
workspace = true

[dependencies.uuid]
features = ["v4"]
workspace = true
