# This file relies on files generated by node2nix tool:
#
#   node2nix -l package-lock.json --nodejs-10 -c node-composition.nix
#
# It is used to bundle rpc proto files from mayastor repo to moac nix package.

{pkgs ? import <nixpkgs> {
  inherit system;
}, system ? builtins.currentSystem}:

let
  result = import ./node-composition.nix {
    inherit pkgs system;
  };
in
result // {
  package = result.package.override {
    csiProto = ../proto/csi.proto;
    mayastorProto = ../../rpc/proto/mayastor.proto;
    mayastorServiceProto = ../../rpc/proto/mayastor_service.proto;
  };
}
