# This file relies on files generated by node2nix tool:
#
#   node2nix -l package-lock.json --nodejs-12 -c node-composition.nix
#
# It is used to bundle rpc proto files from mayastor repo to moac nix package.

{ pkgs ? import <nixpkgs> { inherit system; }
, system ? builtins.currentSystem
}:
let
  result = import ./node-composition.nix { inherit pkgs system; };
in
result // rec {
  package = result.package.override {
    csiProto = ../proto/csi.proto;
    mayastorProto = ../../rpc/proto/mayastor.proto;
    # Prepare script is executed only if npm install is run without any
    # arguments. node2path runs it with a number of args so we must run
    # in manually in postInstall hook :-/
    postInstall = ''
      npm run compile
      npm run prepare
      # Remove makefiles, object files, etc. of bindings that would otherwise
      # reference npm, node sources and other packages not needed at runtime
      find node_modules/grpc-uds/build -name grpc_node.node -o -type f -exec rm '{}' \;
      find node_modules/grpc-uds/build -type f -exec strip '{}' \;
    '';
    # add nodejs and busybox to this variable to set it later to ammend the
    # path variable. This makes it easer to exec into the container
    env = pkgs.stdenv.lib.makeBinPath [ pkgs.busybox pkgs.nodejs-slim-12_x ];
  };
}
