{{- range .Values.mayastorPools }}
---
apiVersion: "openebs.io/v1alpha1"
kind: MayastorPool
metadata:
  # Name can be anything as long as it is unique
  name: pool-on-{{ .node }}
  # or let k8s to generate a unique pool name
  #generateName: pool-
  namespace: {{ $.Release.Namespace }}
spec:
  node: {{ .node }}
  # ATM only one disk device is supported (i.e. /dev/nvme1n1)
  disks: ["{{ .device }}"]
{{- end }}