apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-test-pvc-nvmf
spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
  # storageClassName: mayastor-iscsi
  storageClassName: mayastor-nvmf
