use super::{
    cli::de,
    error::Error,
    options::THIN_POOL_LV,
    vg_pool::{PoolLv, ThinPool, VolumeGroup},
    CmnQueryArgs,
};
use crate::{
    bdev::PtplFileOps,
    bdev_api::{bdev_create, BdevError},
    core::{
        snapshot::ISnapshotDescriptor, CloneParams, NvmfShareProps, Protocol, PtplProps, Share,
        SnapshotParams, UnshareProps, UntypedBdev, UpdateProps,
    },
    lvm::{
        cli::LvmCmd,
        dm_setup::{DmSetup, DmState, DmTable},
        property::{Property, PropertyType},
    },
    pool_backend::PoolBackend,
};

use parking_lot::Mutex;
use std::{
    collections::HashMap,
    ops::{Deref, DerefMut},
    pin::Pin,
    sync::LazyLock,
};

/// Imported volumes by uuid. bdev_as_replica is synchronous, so it finds a
/// bdev's volume here instead of asking lvm.
static IMPORTED: LazyLock<Mutex<HashMap<String, LogicalVolume>>> = LazyLock::new(Default::default);

/// Different list options for a logical volume.
#[derive(Default, Debug)]
pub(crate) struct QueryArgs {
    /// Pertaining the volume group parent.
    vg: super::vg_pool::QueryArgs,
    /// Pertaining the logical volume itself.
    lv: CmnQueryArgs,
    /// Our lv's are "special", as in we set the uuid to the name, and add the
    /// name as a lv_tag (LVM_TAG.lv.name=name)
    regular_lv: bool,
}
impl QueryArgs {
    /// Builder-like creating a default `Self`.
    pub(crate) fn new() -> Self {
        Self::default()
    }
    /// Add the VG query args.
    pub(crate) fn with_vg(self, vg: CmnQueryArgs) -> Self {
        Self {
            vg: vg.into(),
            ..self
        }
    }
    /// Add the LV query args.
    pub(crate) fn with_lv(self, lv: CmnQueryArgs) -> Self {
        Self { lv, ..self }
    }
    /// Get a comma-separated list of query selection args.
    /// todo: should be Display trait?
    pub(super) fn query(&self) -> Result<String, Error> {
        let mut select = self.vg.query()?;
        let args = &self.lv;

        if self.regular_lv {
            if let Some(lv_name) = &args.name {
                super::is_alphanumeric("lv_name", lv_name)?;
                select.push_str(&format!("lv_name={lv_name},"));
            }
            if let Some(lv_uuid) = &args.uuid {
                super::is_alphanumeric("lv_uuid", lv_uuid)?;
                select.push_str(&format!("lv_uuid={lv_uuid},"));
            }
        } else {
            if let Some(name) = &args.name {
                super::is_alphanumeric("name", name)?;
                select.push_str(&format!(
                    "lv_tags={},",
                    Property::LvName(name.to_string()).tag()
                ));
            }
            if let Some(lv_name) = &args.uuid {
                super::is_alphanumeric("lv_name", lv_name)?;
                select.push_str(&format!("lv_name={lv_name},"));
            }
        }

        if let Some(lv_tag) = &args.tag {
            select.push_str(&format!("lv_tags={lv_tag},"));
        }
        Ok(select)
    }
}

/// A Logical Volume (LV) is a virtual block device that can be used by the
/// system or applications.
/// Each block of data in an LV is stored on one or more PV in the VG, according
/// to algorithms implemented by Device Mapper (DM) in the kernel.
#[derive(Debug, Clone, Deserialize)]
pub struct LogicalVolume {
    /// The LV uuid.
    /// This is generated by LVM and we cannot specify a particular value.
    #[allow(dead_code)]
    lv_uuid: String,
    /// The LV name.
    /// We set this to the Replica UUID.
    lv_name: String,
    /// The name of the parent VG.
    vg_name: String,
    /// The uuid of the parent VG.
    /// This is generated by LVM and we cannot specify a particular value.
    vg_uuid: String,
    #[serde(deserialize_with = "de::number_from_string")]
    vg_extent_size: u64,
    /// The LV path.
    /// The logical volume full path name is /dev/<vg_name>/<lv_name>.
    #[serde(rename = "lv_path")]
    path: String,
    /// Size of the LV.
    #[serde(rename = "lv_size")]
    #[serde(deserialize_with = "de::number_from_string")]
    size: u64,
    /// Tags of the LV converted to our properties.
    #[serde(rename = "lv_tags")]
    #[serde(deserialize_with = "de::comma_separated")]
    tags: Vec<Property>,
    /// Tags of the parent VG converted to our properties.
    #[serde(rename = "vg_tags")]
    #[serde(deserialize_with = "de::comma_separated")]
    vg_tags: Vec<Property>,
    /// The LV attribute string. Its first character is the volume type, one
    /// of '-' linear (thick), 'V' thin volume, 't' thin pool or 'e' metadata.
    #[serde(rename = "lv_attr")]
    attr: String,
    /// Percentage of a thin volume which is mapped, None for a thick volume.
    #[serde(deserialize_with = "de::opt_percent")]
    data_percent: Option<f64>,
    /// The chunk size of its thin pool, for a thin volume.
    #[serde(skip)]
    thin_chunk: Option<u64>,

    #[serde(skip)]
    runtime: RunLogicalVolume,
}

/// Runtime settings for the LogicalVolume.
#[derive(Debug, Default, Clone)]
pub struct RunLogicalVolume {
    /// The protocol of the SPDK Bdev which is created against the lv_path.
    /// This is a mirror of the equivalent LV property tag.
    share: Protocol,
    /// LV's are created with name as a tag, so we have to probe the tags and
    /// set name if we find the tag.
    /// This is a mirror of the equivalent LV property tag.
    name: Option<String>,
    /// The entity id which owns this resource, eg: the parent volume.
    /// This is a mirror of the equivalent LV property tag.
    entity_id: Option<String>,

    /// SPDK Bdev parameters which are needed by LVM.
    bdev: Option<BdevOpts>,
    /// When modifying the properties, we may fail to update the LVM LV tags.
    /// In such case, set the dirty flag.
    tags_dirty: bool,
    /// Number of clones created from this volume when it is a snapshot.
    /// Filled in at query time, because descriptors are built synchronously.
    snap_clones: u64,
}

/// Runtime settings for the LogicalVolume.
#[derive(Debug, Default, Clone)]
pub(crate) struct BdevOpts {
    /// The share URI of the SPDK Bdev which is created against the lv_path.
    share_uri: Option<String>,
    /// The URI of the SPDK Bdev which is created against the lv_path.
    open_uri: String,
    allowed_hosts: Vec<String>,
    share: Protocol,
    size: u64,
}
impl From<UntypedBdev> for BdevOpts {
    fn from(bdev: UntypedBdev) -> Self {
        Self {
            share_uri: bdev.share_uri(),
            open_uri: bdev.bdev_uri_original_str().unwrap_or_default(),
            allowed_hosts: bdev.allowed_hosts(),
            share: bdev.shared().unwrap_or_default(),
            size: bdev.size_in_bytes(),
        }
    }
}
impl BdevOpts {
    fn update_from(&mut self, to: Self) {
        self.share_uri = to.share_uri;
        self.allowed_hosts = to.allowed_hosts;
        self.share = to.share;
    }
    /// Get a reference to the original bdev uri.
    pub(crate) fn uri(&self) -> &str {
        &self.open_uri
    }
}

impl Deref for LogicalVolume {
    type Target = RunLogicalVolume;

    fn deref(&self) -> &Self::Target {
        &self.runtime
    }
}
impl DerefMut for LogicalVolume {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.runtime
    }
}

#[derive(Debug, Deserialize)]
struct LogicalVolumeList {
    lv: Vec<LogicalVolume>,
}

impl LogicalVolume {
    /// Create a new logical volume for the given vg uuid.
    pub(crate) async fn create(
        pool: &VolumeGroup,
        args: crate::pool_backend::ReplicaArgs,
        share: Protocol,
        spdk: bool,
    ) -> Result<LogicalVolume, Error> {
        info!(
            name = args.name,
            uuid = args.uuid,
            vg_name = pool.name(),
            "Creating LVM Logical Volume"
        );

        let error = match pool.create_lvoli(&args, share, spdk).await {
            Ok(_) => Ok(None),
            Err(error @ Error::Exists { .. }) => Ok(Some(error)),
            Err(error) => Err(error),
        }?;
        let lvol = Self::lookup(
            &QueryArgs::new()
                .with_lv(CmnQueryArgs::ours_if(spdk).uuid(&args.uuid))
                .with_vg(CmnQueryArgs::ours_if(spdk).uuid(pool.uuid())),
        )
        .await?;

        let Some(error) = error else {
            return Ok(lvol);
        };

        snafu::ensure!(lvol.name().as_deref() == Some(&args.name), error);
        snafu::ensure!(lvol.uuid() == args.uuid, error);
        snafu::ensure!(lvol.size() == args.size, error);
        snafu::ensure!(lvol.thin() == args.thin, error);
        snafu::ensure!(lvol.entity_id() == args.entity_id.as_ref(), error);
        snafu::ensure!(lvol.share_proto().unwrap_or_default() == share, error);

        info!(
            name = args.name,
            uuid = args.uuid,
            vg_name = pool.name(),
            "LVM LogicalVolume imported successfully"
        );

        Ok(lvol)
    }

    /// Lookup a single logical volume.
    pub(crate) async fn lookup(args: &QueryArgs) -> Result<Self, Error> {
        let vgs = Self::list(args).await?;
        vgs.into_iter().next().ok_or(Error::LvNotFound {
            query: args.query().unwrap_or_else(|e| e.to_string()),
        })
    }

    /// List logical volumes using the provided options as query criteria.
    /// All lv's are imported and all imports must succeed.
    pub(crate) async fn list(opts: &QueryArgs) -> Result<Vec<LogicalVolume>, Error> {
        let mut g_error = Ok(());
        let mut lvs = Self::fetch(opts).await?;
        for lv in &mut lvs {
            match lv.import().await {
                Ok(_) => {}
                Err(error) => {
                    tracing::error!(
                        "Failed to import {vg_name}/{lv_name}: {error}",
                        vg_name = lv.vg_name,
                        lv_name = lv.lv_name,
                    );
                    g_error = Err(error);
                }
            }
        }
        g_error?;
        Ok(lvs)
    }

    /// Suspends the [`LogicalVolume`].
    ///
    /// # NOTES
    ///
    /// See details from [`DmSetup::suspend`].
    ///
    /// # WARNING
    ///
    /// The device is only suspended once the open count reaches 0.
    /// This means the device might not be suspended after the suspend call completes.
    /// You should consider using awaiting till [`DmState`] is [`DmState::SUSPENDED`].
    pub async fn dm_suspend(&mut self) -> Result<DmState, Error> {
        DmSetup::suspend(&self.path).await?;
        self.dm_state().await
    }
    /// Resumes/Un-suspends the [`LogicalVolume`].
    ///
    /// # NOTES
    ///
    /// See details from [`DmSetup::resume`].
    pub async fn dm_resume(&mut self) -> Result<DmState, Error> {
        DmSetup::resume(&self.path).await?;
        self.dm_state().await
    }

    /// Retrieve the [`DmState`] of the [`LogicalVolume`].
    pub async fn dm_state(&self) -> Result<DmState, Error> {
        DmSetup::state(&self.path).await
    }

    /// Retrieve the device-mapper table for the [`LogicalVolume`].
    pub async fn table(&self) -> Result<DmTable, Error> {
        DmSetup::table(self.path()).await
    }

    /// A very simple way of making the [`LogicalVolume`] return -EIO for all I/O.
    ///
    /// Returns the previous device-mapper table for restoring.
    pub async fn bork(&mut self) -> Result<DmTable, Error> {
        let current = DmSetup::table(self.path()).await?;

        let sz = self.sz().await?;
        let table = format!("0 {sz} error");
        DmSetup::load(self.path(), DmTable(table)).await?;
        self.dm_resume().await.ok();
        Ok(current)
    }

    async fn sz(&self) -> Result<u64, Error> {
        let output = LvmCmd::blk_dev()
            .arg("--getsz")
            .arg(self.path())
            .output()
            .await?;
        let output_str = String::from_utf8_lossy(&output.stdout).to_string();
        let sz_str = output_str.trim_end();
        sz_str.parse::<u64>().map_err(|error| Error::Internal {
            error: error.to_string(),
        })
    }

    /// Undoes a borked [`LogicalVolume`] by re-applying the previous device-mapper table.
    pub async fn unbork(&mut self, table: DmTable) -> Result<DmState, Error> {
        DmSetup::load(self.path(), table).await?;
        self.dm_resume().await
    }

    /// Retrieve the device path of the [`LogicalVolume`].
    pub fn path(&self) -> &str {
        &self.path
    }

    /// Fetch logical volumes using the provided options as query criteria.
    /// Unlike [`Self::list`], nothing is imported.
    /// Our thin pool is internal to the backend and is never listed.
    pub(super) async fn fetch(opts: &QueryArgs) -> Result<Vec<LogicalVolume>, Error> {
        let mut args = vec![
            "--report-format=json",
            "--options=lv_name,lv_uuid,lv_size,lv_path,lv_tags,vg_name,vg_uuid,vg_tags,vg_extent_size,lv_attr,data_percent",
            "--units=b",
            "--nosuffix",
            "-q",
        ];
        let select = opts.query()?;
        let select_query = format!("--select={select}");
        if !select.is_empty() {
            args.push(select_query.trim_end_matches(','));
        }

        let mut report: LogicalVolumeList =
            LvmCmd::lv_list().args(args.as_slice()).report().await?;

        report.lv.retain(|lv| lv.lv_name != THIN_POOL_LV);
        Self::load_thin_chunks(&mut report.lv).await?;
        report.lv.iter_mut().for_each(|lv| lv.import_attrs());

        Ok(report.lv)
    }

    /// Set the chunk size of our thin pool on each thin volume.
    async fn load_thin_chunks(lvs: &mut [LogicalVolume]) -> Result<(), Error> {
        let mut vg_names: Vec<String> = lvs
            .iter()
            .filter(|lv| lv.thin())
            .map(|lv| lv.vg_name.clone())
            .collect();
        vg_names.sort();
        vg_names.dedup();
        let select = format!("lv_name={THIN_POOL_LV}");
        let thinpools = PoolLv::list(&vg_names, Some(&select)).await?;
        for lv in lvs.iter_mut().filter(|lv| lv.thin()) {
            lv.thin_chunk = ThinPool::find(&thinpools, &lv.vg_name).map(|pool| pool.chunk());
        }
        Ok(())
    }

    /// Destroy the logical volume.
    /// This unloads the lvol from the Bdev module first and then proceeds to
    /// remove the lv from the parent volume group.
    /// A volume which still has snapshots is refused.
    pub(crate) async fn destroy(mut self) -> Result<(), Error> {
        if !self.is_snap() && !self.snapshots().await?.is_empty() {
            return Err(Error::HasLiveSnapshots {
                volume: self.uuid().to_string(),
            });
        }
        self.export_bdev().await?;
        let ptpl = self.ptpl();
        self.remove().await?;
        ptpl.destroy().ok();
        Ok(())
    }

    /// List this volume's snapshots, the volumes tagged with our uuid as their
    /// parent.
    pub(super) async fn snapshots(&self) -> Result<Vec<LogicalVolume>, Error> {
        let query = QueryArgs::new().with_lv(CmnQueryArgs::any()).with_vg(
            CmnQueryArgs::any()
                .uuid(self.vg_uuid())
                .named(self.vg_name()),
        );
        let uuid = self.uuid();
        Ok(Self::fetch(&query)
            .await?
            .into_iter()
            .filter(|lv| lv.snap_parent_id().as_deref() == Some(uuid))
            .collect())
    }

    /// Count the clones of the given snapshot among the volumes.
    pub(super) fn count_clones(volumes: &[LogicalVolume], snapshot_uuid: &str) -> u64 {
        volumes
            .iter()
            .filter(|lv| lv.snapshot_uuid_prop().as_deref() == Some(snapshot_uuid))
            .count() as u64
    }

    /// Count the clones of this snapshot within its volume group.
    pub(super) async fn clone_count(&self) -> Result<u64, Error> {
        let query = QueryArgs::new().with_lv(CmnQueryArgs::ours()).with_vg(
            CmnQueryArgs::any()
                .uuid(self.vg_uuid())
                .named(self.vg_name()),
        );
        let volumes = Self::fetch(&query).await?;
        Ok(Self::count_clones(&volumes, self.uuid()))
    }

    /// Take a snapshot of this thin volume.
    /// The same lvcreate that makes the snapshot also stores the parameters as
    /// its tags, so a snapshot never exists without them.
    /// The snapshot is metadata-only. It is left inactive and never gets a
    /// bdev.
    pub(super) async fn snapshot(&self, params: SnapshotParams) -> Result<LogicalVolume, Error> {
        if !self.thin() {
            return Err(Error::SnapshotThick {
                volume: self.uuid().to_string(),
            });
        }
        let (Some(snap_uuid), Some(snap_name)) = (params.snapshot_uuid(), params.name()) else {
            return Err(Error::Internal {
                error: "snapshot parameters require a name and a uuid".to_string(),
            });
        };
        let create_time = snap_create_time(params.create_time());
        let entity_id = params.entity_id().unwrap_or_default();
        let txn_id = params.txn_id().unwrap_or_default();
        super::is_valid_tag_value("snapshot name", &snap_name)?;
        super::is_valid_tag_value("entity id", &entity_id)?;
        super::is_valid_tag_value("transaction id", &txn_id)?;
        let eexists = format!(
            "Logical Volume \"{snap_uuid}\" already exists in volume group \"{}\"",
            self.vg_name
        );

        let create = LvmCmd::lv_create()
            .args(["-s", &format!("{}/{}", self.vg_name, self.lv_name)])
            .args(["-n", &snap_uuid])
            .tag(Property::SnapName(snap_name))
            .tag(Property::SnapParentId(self.uuid().to_string()))
            .tag_if(!entity_id.is_empty(), Property::SnapEntityId(entity_id))
            .tag_if(!txn_id.is_empty(), Property::SnapTxnId(txn_id))
            .tag(Property::SnapCreateTime(create_time))
            .tag_if(self.ours(), Property::Lvm);
        match create.run().await {
            Err(Error::LvmBinErr { error, .. }) if error.starts_with(&eexists) => {
                Err(Error::Exists { error })
            }
            _else => _else,
        }?;

        let query = QueryArgs::new()
            .with_lv(CmnQueryArgs::any().uuid(&snap_uuid))
            .with_vg(
                CmnQueryArgs::any()
                    .uuid(self.vg_uuid())
                    .named(self.vg_name()),
            );
        let mut snaps = Self::fetch(&query).await?;
        snaps.pop().ok_or_else(|| Error::Internal {
            error: format!("snapshot {snap_uuid} not found after it was created"),
        })
    }

    /// Create a writable clone of this snapshot.
    /// The clone is a thin snapshot of the snapshot, activated and tagged as a
    /// regular replica, plus a tag naming this snapshot as its source.
    pub(super) async fn clone_snap(&self, params: CloneParams) -> Result<LogicalVolume, Error> {
        let (Some(clone_uuid), Some(clone_name)) = (params.clone_uuid(), params.clone_name())
        else {
            return Err(Error::Internal {
                error: "clone parameters require a name and a uuid".to_string(),
            });
        };

        super::is_valid_tag_value("clone name", &clone_name)?;
        let eexists = format!(
            "Logical Volume \"{clone_uuid}\" already exists in volume group \"{}\"",
            self.vg_name
        );
        let query = QueryArgs::new()
            .with_lv(CmnQueryArgs::any().uuid(&clone_uuid))
            .with_vg(
                CmnQueryArgs::any()
                    .uuid(self.vg_uuid())
                    .named(self.vg_name()),
            );

        let create = LvmCmd::lv_create()
            .args(["-s", &format!("{}/{}", self.vg_name, self.lv_name)])
            .args(["-n", &clone_uuid])
            .args(["--setactivationskip", "n"])
            .args(["--activate", "y"])
            .tag(Property::LvName(clone_name))
            .tag(Property::LvShare(Protocol::Off))
            .tag(Property::LvSnapshotUuid(self.uuid().to_string()))
            .tag_if(self.ours(), Property::Lvm);
        match create.run().await {
            Ok(()) => {}
            // A clone of this snapshot with the same uuid is a retried create.
            Err(Error::LvmBinErr { error, .. }) if error.starts_with(&eexists) => {
                return match Self::lookup(&query).await {
                    Ok(clone) if clone.snapshot_uuid_prop().as_deref() == Some(self.uuid()) => {
                        Ok(clone)
                    }
                    _ => Err(Error::Exists { error }),
                };
            }
            Err(error) => return Err(error),
        }

        match Self::lookup(&query).await {
            Ok(clone) => Ok(clone),
            Err(error) => {
                // Do not leave a clone behind which the caller never got.
                let path = format!("{}/{clone_uuid}", self.vg_name);
                if let Err(error) = LvmCmd::lv_remove().arg(&path).arg("-y").run().await {
                    warn!(path, %error, "Failed to remove the clone after its lookup failed");
                }
                Err(error)
            }
        }
    }

    /// Rebuild the snapshot parameters persisted as tags on this snapshot.
    pub(super) fn snap_params(&self) -> SnapshotParams {
        SnapshotParams::new(
            self.property(&PropertyType::SnapEntityId)
                .and_then(|p| p.SnapEntityId()),
            self.snap_parent_id(),
            self.property(&PropertyType::SnapTxnId)
                .and_then(|p| p.SnapTxnId()),
            self.property(&PropertyType::SnapName)
                .and_then(|p| p.SnapName()),
            Some(self.lv_name.clone()),
            self.property(&PropertyType::SnapCreateTime)
                .and_then(|p| p.SnapCreateTime()),
            false,
        )
    }

    /// The number of clones of this snapshot, as counted at query time.
    pub(super) fn snap_clones(&self) -> u64 {
        self.snap_clones
    }
    /// Record the number of clones of this snapshot.
    pub(super) fn set_snap_clones(&mut self, clones: u64) {
        self.snap_clones = clones;
    }

    /// Import the Logical Volume.
    /// This is a required step after creating the LV, which adds the name and
    /// the share protocol as property tags.
    /// The LV is then imported as an spdk BDEV, which allows it to be shared
    /// via nvmf or open locally (ex: by the nexus).
    /// Snapshots are metadata-only and never get a bdev.
    pub(crate) async fn import(&mut self) -> Result<(), Error> {
        if !self.ours() || !self.vg_ours() || self.is_snap() {
            return Ok(());
        }
        self.import_bdev().await
    }

    /// Resize the logical volume AND the SPDK Bdev to the given size.
    /// > Note: If the SPDK Bdev fails to be resized, then the LV size is
    /// > reverted back.
    /// # Warning: If the SPDK Bdev is not loaded, then it is also not resized
    /// and the operation still succeeds.
    pub(crate) async fn resize(&mut self, size: u64) -> Result<(), Error> {
        let prev_size = self.size;
        self.resize_lv(size).await?;

        if let Err(error) = self.resize_bdev(size).await {
            self.resize_lv(prev_size).await.ok();
            return Err(error);
        }

        Ok(())
    }

    /// Export out the SPDK bdev.
    /// The bdev is unshared (if shared) and closed, allowing the logical volume
    /// to be closed and/or destroyed.
    pub(super) async fn export_bdev(&mut self) -> Result<(), Error> {
        IMPORTED.lock().remove(self.uuid());
        let Ok(bdev) = self.bdev_opts() else {
            // Nothing to do if the bdev was not setup...
            return Ok(());
        };
        let uri = bdev.open_uri.clone();
        crate::spdk_run!(async move {
            if let Ok(mut bdev) = Self::bdev(&uri) {
                // todo: must we error if we can't unshare?
                Self::bdev_unshare(&mut bdev).await?;
            }

            let bdev = crate::bdev::uri::parse(&uri).unwrap();
            match bdev.destroy().await {
                Ok(()) | Err(BdevError::BdevNotFound { .. }) => Ok(()),
                Err(source) => Err(Error::BdevExport { source }),
            }
        })?;
        self.bdev = None;
        Ok(())
    }

    /// Remove (delete really) the logical volume from the parent volume group.
    /// # Note: if the Bdev is not unloaded first, then lv removal will be reject
    /// by the lvm driver.
    async fn remove(self) -> Result<(), Error> {
        LvmCmd::lv_remove().arg(self.path).arg("-y").run().await?;

        info!("lvm volume {} deleted", self.lv_name);
        Ok(())
    }

    /// Resize only the logical volume to the given size (not the SPDK Bdev).
    async fn resize_lv(&mut self, size: u64) -> Result<(), Error> {
        let size_str = format!("-L{size}b");
        match LvmCmd::lv_resize()
            .arg(&self.path)
            .arg(size_str)
            .arg("-y")
            .run()
            .await
        {
            Ok(()) => Ok(()),
            // not great, but not sure how else to map the error otherwise...
            Err(Error::LvmBinErr { error, .. }) if error.starts_with("Insufficient free space") => {
                Err(Error::NoSpace { error })
            }
            Err(error) => Err(error),
        }
    }

    /// Resize the logical volume's SPDK Bdev to the given size.
    async fn resize_bdev(&mut self, size: u64) -> Result<(), Error> {
        let Ok((bdev, uri)) = self.bdev_mut_uri() else {
            // If the Bdev is not open, we don't need to resize it!?
            return Ok(());
        };
        let (rc, size) = crate::spdk_run!(async move {
            let mut bdev = Self::bdev(&uri)?;

            let blk_cnt = size / bdev.block_len() as u64;

            use spdk_rs::libspdk::spdk_bdev_notify_blockcnt_change;
            let rc =
                unsafe { spdk_bdev_notify_blockcnt_change(bdev.unsafe_inner_mut_ptr(), blk_cnt) };
            Ok((rc, bdev.size_in_bytes()))
        })?;
        if rc != 0 {
            error!("failed to notify block cnt change on lvol: {rc}");
            return Err(Error::BdevShareUri {});
        }
        bdev.size = size;
        Ok(())
    }

    async fn sync_share_opts(&mut self) -> Result<(), Error> {
        let Some(opts) = &self.bdev else {
            return Ok(());
        };
        let properties = vec![
            Property::LvShare(opts.share),
            Property::LvAllowedHosts(opts.allowed_hosts.clone()),
        ];

        self.set_properties(properties).await
    }
    async fn sync_share_protocol(&mut self, protocol: Protocol) -> Result<(), Error> {
        self.set_property(Property::LvShare(protocol)).await?;
        self.share = protocol;
        Ok(())
    }
    async fn build_set_properties_args(&self, properties: Vec<Property>) -> Vec<String> {
        let mut args = Vec::new();
        for property in properties {
            args.extend(self.build_set_property_args(property).await);
        }
        args
    }
    async fn build_set_property_args(&self, property: Property) -> Vec<String> {
        let existing = self.properties(&property.type_());
        let mut add = true;
        let mut args = existing
            .iter()
            .flat_map(|old| match old == &property {
                true => {
                    add = false;
                    None
                }
                false => Some(old.del()),
            })
            .collect::<Vec<_>>();
        if add {
            args.push(property.add());
        }
        args
    }
    async fn set_properties(&mut self, properties: Vec<Property>) -> Result<(), Error> {
        let args = self.build_set_properties_args(properties).await;
        if args.is_empty() {
            return Ok(());
        }
        let result = LvmCmd::lv_change().args(args).arg(&self.path).run().await;
        if result.is_err() {
            self.tags_dirty = true;
        }
        result
    }
    pub(crate) async fn set_property(&mut self, property: Property) -> Result<(), Error> {
        self.set_properties(vec![property]).await
    }

    async fn bdev_sync_props(
        bdev: &mut UntypedBdev,
        protocol: Protocol,
        ptpl: impl PtplFileOps,
        allowed_hosts: Vec<String>,
    ) -> Result<(), Error> {
        match protocol {
            Protocol::Nvmf => {
                let props = NvmfShareProps::new()
                    .with_allowed_hosts(allowed_hosts)
                    .with_ptpl(ptpl.create().map_err(|source| Error::BdevShare {
                        source: crate::core::CoreError::Ptpl {
                            reason: source.to_string(),
                        },
                    })?);
                Self::bdev_share_nvmf(bdev, Some(props)).await?;
            }
            Protocol::Off => {
                Self::bdev_unshare(bdev).await?;
            }
        }

        Ok(())
    }

    /// Import the Logical Volume by loading it via an SPDK bdev using AIO.
    /// todo: Allow using either aio or uring.
    /// todo: Test performance.
    async fn import_bdev(&mut self) -> Result<(), Error> {
        let disk_uri = format!("aio://{}?uuid={}", self.path, self.uuid());

        let allowed_hosts = self
            .property(&PropertyType::LvAllowedHosts)
            .and_then(|p| p.LvAllowedHosts())
            .unwrap_or_default();

        let share = self.share;
        let ptpl = self.ptpl();

        let bdev = crate::spdk_run!(async move {
            if crate::core::UntypedBdev::lookup_by_name(&disk_uri).is_none() {
                bdev_create(&disk_uri)
                    .await
                    .map_err(|source| Error::BdevImport { source })?;
            }

            let mut bdev = Self::bdev(&disk_uri)?;
            Self::bdev_sync_props(&mut bdev, share, ptpl, allowed_hosts).await?;

            Ok(BdevOpts::from(bdev))
        })?;
        self.bdev = bdev.into();
        IMPORTED
            .lock()
            .insert(self.uuid().to_string(), self.clone());
        Ok(())
    }

    /// The imported volume with the given uuid, as it was when imported.
    pub(super) fn imported(uuid: &str) -> Option<LogicalVolume> {
        IMPORTED.lock().get(uuid).cloned()
    }
    fn bdev_mut(&mut self) -> Result<&mut BdevOpts, Error> {
        let Some(bdev) = self.bdev.as_mut() else {
            // Nothing to do if the bdev was not setup...
            return Err(Error::BdevMissing {});
        };
        Ok(bdev)
    }
    fn bdev_mut_uri(&mut self) -> Result<(&mut BdevOpts, String), Error> {
        let bdev = self.bdev_mut()?;
        let uri = bdev.open_uri.clone();
        Ok((bdev, uri))
    }
    pub(crate) fn bdev_opts(&self) -> Result<&BdevOpts, Error> {
        let Some(uri) = self.bdev.as_ref() else {
            // Nothing to do if the bdev was not setup...
            return Err(Error::BdevMissing {});
        };
        Ok(uri)
    }

    fn import_attrs(&mut self) {
        self.name = self
            .property(&PropertyType::LvName)
            .and_then(|p| p.LvName())
            .or_else(|| {
                self.property(&PropertyType::SnapName)
                    .and_then(|p| p.SnapName())
            });
        self.share = self
            .property(&PropertyType::LvShare)
            .and_then(|p| p.LvShare())
            .unwrap_or_default();
        self.entity_id = self
            .property(&PropertyType::LvEntityId)
            .and_then(|p| p.LvEntityId())
            .or_else(|| {
                self.property(&PropertyType::SnapEntityId)
                    .and_then(|p| p.SnapEntityId())
            });
        self.tags_dirty = false;
        tracing::trace!("{self:?}");
    }

    fn property(&self, property: &PropertyType) -> Option<Property> {
        self.tags
            .iter()
            .find(|tag| tag.key() == property.value())
            .cloned()
    }
    fn properties(&self, property: &PropertyType) -> Vec<Property> {
        self.tags
            .iter()
            .filter(|tag| tag.key() == property.value())
            .cloned()
            .collect()
    }
    /// Get the name of the volume group where this logical volume resides.
    pub(crate) fn vg_name(&self) -> &str {
        &self.vg_name
    }
    /// Get the uuid of the volume group where this logical volume resides.
    pub(crate) fn vg_uuid(&self) -> &str {
        &self.vg_uuid
    }
    /// The "apparent" size of the Logical Volume.
    /// If the SPDK Bdev is not open, then it's just the lv size.
    /// If it's open, then it's the smallest between the bdev and the lv.
    pub(crate) fn size(&self) -> u64 {
        match self.bdev.as_ref().map(|b| b.size) {
            None => self.size,
            Some(b_size) => self.size.min(b_size),
        }
    }
    /// Check the lv is thin provisioned (otherwise it's thick).
    pub(crate) fn thin(&self) -> bool {
        self.attr.starts_with('V')
    }
    /// Bytes mapped in the backing store. A thin volume works this out from
    /// its data_percent. A thick volume is always fully allocated.
    pub(crate) fn allocated_bytes(&self) -> u64 {
        if !self.thin() {
            return self.size;
        }
        match self.data_percent {
            Some(percent) => ((self.size as f64) * percent / 100.0) as u64,
            // Our snapshots are inactive thin volumes, and inactive thin
            // volumes report no data_percent.
            None => 0,
        }
    }
    /// The allocation granularity of this volume. That is the chunk size of
    /// its thin pool for a thin volume, and the volume group extent size for
    /// a thick volume or when the chunk size is unknown.
    pub(crate) fn allocation_unit(&self) -> u64 {
        match self.thin_chunk {
            Some(chunk) if self.thin() && chunk > 0 => chunk,
            _ => self.vg_extent_size,
        }
    }
    /// The uuid of the replica this volume is a snapshot of, when it is one.
    pub(super) fn snap_parent_id(&self) -> Option<String> {
        self.property(&PropertyType::SnapParentId)
            .and_then(|p| p.SnapParentId())
    }
    /// Check whether this volume is one of our snapshots.
    pub(super) fn is_snap(&self) -> bool {
        self.snap_parent_id().is_some()
    }
    /// The uuid of the snapshot this volume was cloned from, when it is a
    /// clone.
    pub(super) fn snapshot_uuid_prop(&self) -> Option<String> {
        self.property(&PropertyType::LvSnapshotUuid)
            .and_then(|p| p.LvSnapshotUuid())
    }
    /// LV's are created with name=replica uuid, so we have to "swap" here.
    pub(crate) fn uuid(&self) -> &str {
        &self.lv_name
    }
    /// Check if this LV is owned by us.
    pub(crate) fn ours(&self) -> bool {
        self.tags.contains(&Property::Lvm)
    }
    /// Check if the parent VG is owned by us.
    pub(crate) fn vg_ours(&self) -> bool {
        self.vg_tags.contains(&Property::Lvm)
    }
    /// Get the name of the logical volume.
    pub(crate) fn name(&self) -> &Option<String> {
        &self.name
    }
    /// Get the entity id of the resource which owns this logical volume.
    pub(crate) fn entity_id(&self) -> Option<&String> {
        self.entity_id.as_ref()
    }
    /// Get the URI of the SPDK bdev which is layered on top of the lv.
    pub(crate) fn uri(&self) -> Option<&String> {
        self.bdev.as_ref()?.share_uri.as_ref()
    }
    /// Get the SPDK bdev allowed hosts.
    pub(crate) fn allowed_hosts(&self) -> Option<&Vec<String>> {
        self.bdev.as_ref().map(|b| &b.allowed_hosts)
    }
}

/// These should be part of the Share trait but there are a few things that make
/// it difficult:
/// 1. It uses Pin which is not required for our lvm
/// 2. Some of the functions part of the Share trait are blocking but we're
///    currently using a trampoline between tokio and spdk reactors which makes
///    this difficult.
///
/// todo: would reactor block on help here? we could go the
///    other way and use trampoline from spdk to tokio, but then also hit the
///    problem?
impl LogicalVolume {
    pub(crate) fn bdev(uri: &str) -> Result<UntypedBdev, Error> {
        UntypedBdev::get_by_name(uri).map_err(|_| Error::BdevMissing {})
    }

    async fn bdev_share_nvmf(
        bdev: &mut UntypedBdev,
        props: Option<NvmfShareProps>,
    ) -> Result<String, Error> {
        let mut bdev = Pin::new(bdev);
        match bdev.shared() {
            Some(Protocol::Nvmf) => {
                bdev.as_mut()
                    .update_properties(props.map(Into::into))
                    .await
                    .map_err(|source| Error::BdevShare { source })?;
                bdev.share_uri().ok_or(Error::BdevShareUri {})
            }
            Some(Protocol::Off) | None => bdev
                .share_nvmf(props)
                .await
                .map_err(|source| Error::BdevShare { source }),
        }
    }
    async fn bdev_unshare(bdev: &mut UntypedBdev) -> Result<Option<String>, Error> {
        let mut bdev = Pin::new(bdev);
        match bdev.shared() {
            Some(Protocol::Nvmf) => {
                bdev.as_mut()
                    .unshare(None)
                    .await
                    .map_err(|source| Error::BdevUnshare { source })?;
            }
            Some(Protocol::Off) | None => {}
        }
        Ok(bdev.share_uri())
    }

    /// Share the lvol via nvmf.
    pub(crate) async fn share_nvmf(
        &mut self,
        props: Option<NvmfShareProps>,
    ) -> Result<String, Error> {
        let (bdev, uri) = self.bdev_mut_uri()?;

        let (nqn, bdev_opts) = crate::spdk_run!(async move {
            let mut bdev = Self::bdev(&uri)?;
            let nqn = Self::bdev_share_nvmf(&mut bdev, props).await?;
            Ok((nqn, BdevOpts::from(bdev)))
        })?;

        // todo: add per-bdev locking... to ensure we don't have concurrent spdk
        //  code...
        // todo: BUG: wrong share URI:
        // nqn.2019-05.io.openebs:/dev/sdavg/
        // d514adef-f4ce-4575-b10e-eb301de2cf99 vs
        // nqn.2019-05.io.openebs:d514adef-f4ce-4575-b10e-eb301de2cf99

        bdev.update_from(bdev_opts);
        self.sync_share_opts().await?;

        info!("{:?}: shared as NVMF", self);
        Ok(nqn)
    }

    /// Update the lvol share properties.
    pub(crate) async fn update_share_props<P: Into<Option<UpdateProps>>>(
        &mut self,
        props: P,
    ) -> Result<(), Error> {
        let (bdev, uri) = self.bdev_mut_uri()?;
        let props = props.into();
        let bdev_opts = crate::spdk_run!(async move {
            let mut bdev = Self::bdev(&uri)?;
            Pin::new(&mut bdev)
                .update_properties(props)
                .await
                .map_err(|e| Error::UpdateProps {
                    source: e,
                    name: bdev.name().to_string(),
                })?;
            Ok(BdevOpts::from(bdev))
        })?;
        bdev.update_from(bdev_opts);
        self.sync_share_opts().await?;
        Ok(())
    }

    /// Unshare the nvmf target.
    pub(crate) async fn unshare(&mut self, opts: Option<UnshareProps>) -> Result<(), Error> {
        let (bdev, uri) = self.bdev_mut_uri()?;
        let share = crate::spdk_run!(async move {
            let mut bdev = Self::bdev(&uri)?;
            Self::bdev_unshare(&mut bdev).await
        })?;

        bdev.share_uri = share;
        bdev.share = Protocol::Off;

        if opts.unwrap_or_default().persist {
            self.sync_share_protocol(Protocol::Off).await?;
        }

        info!("{self:?}: unshared");
        Ok(())
    }

    /// Get the shared protocol, if any setup.
    pub(crate) fn share_proto(&self) -> Option<Protocol> {
        self.bdev.as_ref().map(|_| self.share)
    }

    /// Get a `PtplFileOps` from `&self`.
    pub(crate) fn ptpl(&self) -> impl PtplFileOps {
        LvolPtpl::from(self)
    }
}

/// The snapshot create time to store as a tag. Tag values cannot contain
/// spaces, so it is stored as RFC 3339, which the gRPC layer parses back.
/// The caller's time is used when it parses, otherwise the current time.
fn snap_create_time(requested: Option<String>) -> String {
    requested
        .and_then(|time| time.parse::<chrono::DateTime<chrono::Utc>>().ok())
        .unwrap_or_else(chrono::Utc::now)
        .to_rfc3339()
}

pub struct LvolPtpl {
    vg: super::vg_pool::VgPtpl,
    uuid: String,
}
impl LvolPtpl {
    fn vg(&self) -> &super::vg_pool::VgPtpl {
        &self.vg
    }
    fn uuid(&self) -> &str {
        &self.uuid
    }
}
impl From<&LogicalVolume> for LvolPtpl {
    fn from(lvol: &LogicalVolume) -> Self {
        Self {
            vg: VolumeGroup::vg_ptpl(lvol.vg_name()),
            uuid: lvol.uuid().to_string(),
        }
    }
}

impl PtplFileOps for LvolPtpl {
    fn create(&self) -> Result<Option<PtplProps>, std::io::Error> {
        if let Some(path) = self.path() {
            self.vg().create()?;
            if let Some(parent) = path.parent() {
                std::fs::create_dir_all(parent)?;
            }
            return Ok(Some(PtplProps::new(path)));
        }
        Ok(None)
    }

    fn destroy(&self) -> Result<(), std::io::Error> {
        if let Some(path) = self.path() {
            std::fs::remove_file(path)?;
        }
        Ok(())
    }

    fn subpath(&self) -> std::path::PathBuf {
        self.vg()
            .subpath()
            .join("lv/")
            .join(self.uuid())
            .with_extension("json")
    }
}

impl crate::core::LogicalVolume for LogicalVolume {
    fn name(&self) -> String {
        self.name().clone().unwrap_or_default()
    }

    fn uuid(&self) -> String {
        self.lv_name.clone()
    }

    fn pool_name(&self) -> String {
        self.vg_name().into()
    }

    fn pool_uuid(&self) -> String {
        self.vg_uuid().into()
    }

    fn entity_id(&self) -> Option<String> {
        self.entity_id().cloned()
    }

    fn is_thin(&self) -> bool {
        self.thin()
    }

    fn is_read_only(&self) -> bool {
        self.is_snap()
    }

    fn size(&self) -> u64 {
        self.size
    }

    fn committed(&self) -> u64 {
        self.size
    }

    fn allocated(&self) -> u64 {
        self.allocated_bytes()
    }

    fn usage(&self) -> crate::core::logical_volume::LvolSpaceUsage {
        crate::core::logical_volume::LvolSpaceUsage {
            capacity_bytes: self.size(),
            allocated_bytes: self.allocated(),
            cluster_size: self.allocation_unit(),
            // todo: missing this information
            num_clusters: 0,
            num_allocated_clusters: 0,
            allocated_bytes_snapshots: 0,
            num_allocated_clusters_snapshots: 0,
            allocated_bytes_snapshot_from_clone: None,
        }
    }

    fn is_snapshot(&self) -> bool {
        self.is_snap()
    }

    fn is_clone(&self) -> bool {
        self.snapshot_uuid_prop().is_some()
    }

    fn backend(&self) -> PoolBackend {
        PoolBackend::Lvm
    }

    fn snapshot_uuid(&self) -> Option<String> {
        self.snapshot_uuid_prop()
    }

    fn share_protocol(&self) -> Protocol {
        self.share
    }

    fn bdev_share_uri(&self) -> Option<String> {
        self.uri().cloned()
    }

    fn nvmf_allowed_hosts(&self) -> Vec<String> {
        self.allowed_hosts().cloned().unwrap_or_default()
    }

    fn encrypted(&self) -> bool {
        // until we support lvm backend with encryption
        false
    }
}

#[async_trait::async_trait(?Send)]
impl Share for LogicalVolume {
    type Error = Error;
    type Output = String;

    async fn share_nvmf(
        mut self: Pin<&mut Self>,
        props: Option<NvmfShareProps>,
    ) -> Result<Self::Output, Self::Error> {
        self.share_nvmf(props).await
    }
    fn create_ptpl(&self) -> Result<Option<PtplProps>, Self::Error> {
        self.ptpl().create().map_err(|source| Error::BdevShare {
            source: crate::core::CoreError::Ptpl {
                reason: source.to_string(),
            },
        })
    }

    async fn update_properties<P: Into<Option<UpdateProps>>>(
        mut self: Pin<&mut Self>,
        props: P,
    ) -> Result<(), Self::Error> {
        self.as_mut().update_share_props(props).await
    }

    async fn unshare(
        mut self: Pin<&mut Self>,
        opts: Option<UnshareProps>,
    ) -> Result<(), Self::Error> {
        self.deref_mut().unshare(opts).await
    }

    fn shared(&self) -> Option<Protocol> {
        self.share_proto()
    }

    fn share_uri(&self) -> Option<String> {
        self.uri().cloned()
    }

    fn allowed_hosts(&self) -> Vec<String> {
        self.allowed_hosts().cloned().unwrap_or_default()
    }

    fn bdev_uri(&self) -> Option<url::Url> {
        None
    }
    fn bdev_uri_original(&self) -> Option<url::Url> {
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn volume(name: &str, attr: &str, tags: &str) -> LogicalVolume {
        let mut lv: LogicalVolume = serde_json::from_value(serde_json::json!({
            "lv_uuid": format!("{name}-lv-uuid"),
            "lv_name": name,
            "vg_name": "vg",
            "vg_uuid": "vg-uuid",
            "vg_extent_size": "4194304",
            "lv_path": format!("vg/{name}"),
            "lv_size": "33554432",
            "lv_tags": tags,
            "vg_tags": "mayastor",
            "lv_attr": attr,
            "data_percent": "",
        }))
        .unwrap();
        lv.import_attrs();
        lv
    }

    #[test]
    fn clone_counting() {
        let volumes = vec![
            volume("r1", "Vwi-aotz--", "mayastor,mayastor.lv.name=r1"),
            volume(
                "s1",
                "Vwi---tz-k",
                "mayastor,mayastor.snap.name=s1,mayastor.snap.parent_id=r1",
            ),
            volume(
                "c1",
                "Vwi-aotz--",
                "mayastor,mayastor.lv.name=c1,mayastor.lv.snapshot_uuid=s1",
            ),
            volume(
                "c2",
                "Vwi-aotz--",
                "mayastor,mayastor.lv.name=c2,mayastor.lv.snapshot_uuid=s1",
            ),
        ];
        assert_eq!(LogicalVolume::count_clones(&volumes, "s1"), 2);
        assert_eq!(LogicalVolume::count_clones(&volumes, "r1"), 0);
        assert_eq!(LogicalVolume::count_clones(&[], "s1"), 0);
    }

    #[test]
    fn allocation_unit() {
        let mut thin = volume("r1", "Vwi-aotz--", "mayastor");
        assert_eq!(thin.allocation_unit(), 4194304);
        thin.thin_chunk = Some(131072);
        assert_eq!(thin.allocation_unit(), 131072);
        let mut thick = volume("r2", "-wi-ao----", "mayastor");
        thick.thin_chunk = Some(131072);
        assert_eq!(thick.allocation_unit(), 4194304);
    }

    #[test]
    fn create_time() {
        let parse = |time: &str| time.parse::<chrono::DateTime<chrono::Utc>>().unwrap();
        assert_eq!(
            snap_create_time(Some("2024-01-02T03:04:05Z".to_string())),
            "2024-01-02T03:04:05+00:00"
        );
        // the format callers get from Utc::now().to_string()
        let time = snap_create_time(Some("2024-01-02 03:04:05.5 UTC".to_string()));
        assert_eq!(parse(&time), parse("2024-01-02T03:04:05.5Z"));
        assert!(!time.contains(' '));
        for requested in [None, Some("yesterday".to_string())] {
            let before = chrono::Utc::now();
            let time = parse(&snap_create_time(requested));
            assert!(time >= before - chrono::Duration::seconds(1));
            assert!(time <= chrono::Utc::now());
        }
    }
}
