apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ms-volume-claim
spec:
  accessModes:
   - ReadWriteOnce
  # Change to "Block" for raw block device
  volumeMode: Filesystem
  resources:
    requests:
      storage: 64Mi
  storageClassName: mayastor-nvmf
