---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mayastor-nvmf
parameters:
  repl: '1'
  protocol: 'nvmf'
  ioTimeout: '30'
  local: 'yes'
  # It is recommended to use xfs for Mayastor
  # fsType: 'xfs'
provisioner: io.openebs.csi-mayastor
volumeBindingMode: WaitForFirstConsumer
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mayastor-nvmf-3
parameters:
  repl: '3'
  protocol: 'nvmf'
  ioTimeout: '30'
  # It is recommended to use xfs for Mayastor
  # fsType: 'xfs'
provisioner: io.openebs.csi-mayastor
volumeBindingMode: WaitForFirstConsumer
