kind: Pod
apiVersion: v1
metadata:
  name: fio
spec:
  volumes:
    - name: ms-volume
      persistentVolumeClaim:
       claimName: loss-test-pvc-iscsi
  containers:
    - name: fio
      image: nixery.dev/shell/fio/tini
      command: [ "tini", "--" ]
      args:
        - sleep
        - "1000000"
      volumeMounts:
        - mountPath: "/volume"
          name: ms-volume
  nodeSelector:
    node-role.kubernetes.io/master: ""
