[package]
authors = ["Jan Kryl <jan.kryl@mayadata.io>", "Jeffry Molanus <jeffry.molanus@mayadata.io"]
name = "csi"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "mayastor-agent"
path = "src/server.rs"

[[bin]]
name = "mayastor-client"
path = "src/client.rs"

[build-dependencies]
bytes = "0.4"
tonic-build = "0.1.0-beta.1"
prost-build = "0.5.0"

[dependencies]
async-stream = "0.1.2"
bytes = "0.4"
bytesize = "1.0.0"
chrono = "0.4.9"
clap = "2.32"
env_logger = "0.7"
futures = { version = "0.3", default-features = false }
git-version = "0.3.1"

glob = "*"
http = "0.1"
http-body = "0.2"
jsonrpc = { path = "../jsonrpc" }
libc = "0.2"
log = "0.4"
loopdev = "*"
nix = "*"
proc-mounts = "0.2"
prost = "0.5"
prost-derive = "0.5"
prost-types = "0.5"
rpc = { path = "../rpc" }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
sys-mount = "1.2"
tokio = { version = "0.2.8", features = ["full"] }
run_script = "*"
tonic = "0.1.0-beta.1"
tower = "0.3"
[dependencies.blkid]
branch = "blkid-sys"
git = "https://github.com/openebs/blkid"

