[package]
name = "io-engine-tests"
description = "I/O test support library"
version = "0.1.0"
edition = "2018"

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
colored_json = { workspace = true }
crossbeam = { workspace = true }
derive_builder = { workspace = true }
hex = { workspace = true }
md5 = { workspace = true }
nix = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
regex = { workspace = true }
run_script = { workspace = true }
serde_json = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

composer = { path = "../utils/dependencies/composer" }
libnvme-rs = { path = "../libnvme-rs" }
io-engine-api = { path = "../utils/dependencies/apis/io-engine" }
io-engine = { path = "../io-engine" }
io-engine-tests-macros = { path = "./io-engine-tests-macros" }

[dependencies.serde]
features = ["derive"]
workspace = true

[dependencies.spdk-rs]
path = "../spdk-rs"

[dependencies.tokio]
features = ["full"]
workspace = true

[dependencies.uuid]
features = ["v4"]
workspace = true
