name: ImageBuild CI
on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CI: 1

jobs:
  image-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: 'recursive'
      - uses: cachix/install-nix-action@v31.11.0
      - name: Test building the release images
        run: ./scripts/release.sh --skip-publish --build-bins
