name: "no bling-bling tests"
on:
  pull_request:
    paths-ignore:
  push:
    branches:
      - develop
jobs:
  nix-shell:
    name: check and see if it works
    runs-on: self-hosted
    timeout-minutes: 20
    container:
      image: docker.io/nixos/nix
      options: --privileged -v /dev:/dev -v /:/host -v /lib/modules:/lib/modules
    steps:
      - uses: actions/checkout@v2
      - run: 'printf "#!/usr/bin/env bash\nchroot /host /usr/bin/env -i PATH=\"/sbin:/bin:/usr/bin\" iscsiadm \"\$@\"\n" > /bin/mayastor-iscsiadm && chmod +x /bin/mayastor-iscsiadm'
      - run: ln -s /host/bin/kmod /bin/modprobe
      - run: modprobe nbd
      - run: modprobe xfs
      - run: modprobe nvme_tcp
      - run: echo 8192 | tee /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
      - run: rm mayastor/.cargo/config
      - run: rm nvmeadm/.cargo/config
      #- run: nix-env -f shell.nix -i -A 'buildInputs'
      - run: nix-shell --run "./scripts/test.sh"