name: "nix-build with cachix"
on:
  push:
  pull_request:
    paths:
      - '**.nix'
jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
    - uses: cachix/cachix-action@v5
      with:
        name: mayastor
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        attributes: libspdk
