name: Bors CI
on:
  workflow_call:
    inputs:
      trigger:
        required: false
        type: string
        default: "merge_group"
  push:
    branches:
      - staging
      - trying
  merge_group:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']

jobs:
  lint-ci:
    if: github.event_name != 'pull_request' || inputs.trigger == 'try' || startsWith(github.head_ref, 'mergify/merge-queue/')
    uses: ./.github/workflows/lint.yml
  int-ci:
    if: github.event_name != 'pull_request' || inputs.trigger == 'try' || startsWith(github.head_ref, 'mergify/merge-queue/')
    uses: ./.github/workflows/unit-int.yml
  bdd-ci:
    if: github.event_name != 'pull_request' || inputs.trigger == 'try' || startsWith(github.head_ref, 'mergify/merge-queue/')
    uses: ./.github/workflows/bdd.yml
  image-ci:
    if: github.event_name != 'pull_request' || inputs.trigger == 'try' || startsWith(github.head_ref, 'mergify/merge-queue/')
    uses: ./.github/workflows/image-pr.yml
  bors-ci:
    if: ${{ !cancelled() && (github.event_name != 'pull_request' || inputs.trigger == 'try' || startsWith(github.head_ref, 'mergify/merge-queue/')) }}
    needs:
      - lint-ci
      - int-ci
      - bdd-ci
      - image-ci
    runs-on: ubuntu-latest
    steps:
      - name: CI succeeded
        run: |
          if [[ "${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            exit 1
          fi
          exit 0
