name: Lint Commit Messages
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install CommitLint and Dependencies
        run: npm install @commitlint/config-conventional @commitlint/cli
      - name: Ensure follows conventional commits
        run:
            TEMP=$(mktemp)
            nix-shell default.nix -A convco --run "convco changelog > ${TEMP}"
            diff CHANGELOG.md ${TEMP}
            rm ${TEMP}

