name: "Lint and style Checks"
on:
  pull_request:
jobs:
  Clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: cachix/install-nix-action@v10
      - run: nix-shell --run "pre-commit run --from-ref HEAD~1 --to-ref HEAD"
  Semistandard:
    name: SemiStandard
    runs-on: ubuntu-latest
    container:
      image: docker.io/mayadata/ms-buildenv:latest
    steps:
      - uses: actions/checkout@master
      - run: git ls-files | grep '\.js$' | xargs -r ./scripts/js-check.sh
        shell: bash
