name: Integration CI
on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CI: 1

jobs:
  int-tests:
    runs-on: cncf-ubuntu-16-64-x86
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - uses: cachix/install-nix-action@v31.10.6
        with:
          github_access_token: ''

      - name: Inject github token to nix config
        run: |
          cat <<EOF | sudo tee -a /etc/nix/nix.conf
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          trusted-users = root runner
          EOF

      - name: Restart Nix daemon
        run: sudo systemctl restart nix-daemon

      - name: Pre-populate nix-shell
        run: |
          export NIX_PATH=nixpkgs=$(jq '.nixpkgs.url' spdk-rs/nix/sources.json -r)
          echo "NIX_PATH=$NIX_PATH" >> $GITHUB_ENV
          nix-shell --run "echo" shell.nix

      - name: Handle Rust dependencies caching
        uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ startsWith(github.ref_name, 'release/') || github.ref_name == 'develop' }}

      - name: Build binaries
        run: nix-shell --run "cargo build --bins --features=io-engine-testing"

      - name: Setup Test Pre-Requisites
        run: |
          sudo sysctl -w vm.nr_hugepages=3584
          sudo debconf-communicate <<< "set man-db/auto-update false" || true
          sudo dpkg-reconfigure man-db || true
          ulimit -c unlimited
          sudo apt-get update
          sudo apt-get install linux-modules-extra-$(uname -r)
          for module in nvme_tcp nbd nvme_rdma; do
            sudo modprobe $module
          done
          sudo apt-get install gdb
          # Check if nvme config is valid, otherwise apply it
          sudo ./scripts/nvme-conf.sh --check --apply --overwrite

      - name: Configure Docker logging driver
        run: |
          echo '{"log-driver": "journald"}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Run Rust Tests
        run: |
          echo "TEST_START_DATE=$(date +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
          nix-shell --run "./scripts/cargo-test.sh"

      - name: Check Coredumps
        if: always()
        run: sudo ./scripts/check-coredumps.sh --since "${TEST_START_DATE}"

      - name: Cleanup
        if: always()
        run: nix-shell --run "./scripts/clean-cargo-tests.sh"

      - name: Run JS Grpc Tests
        run: |
          echo "TEST_START_DATE=$(date +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
          nix-shell --run "./scripts/grpc-test.sh"

      - name: Create JS Report
        if: always()
        run: |
          mkdir -p ci-report/js
          for file in *-xunit-report.xml; do
            echo "<testsuites>" > "ci-report/js/$file"
            cat $file >> "ci-report/js/$file"
            echo "</testsuites>" >> "ci-report/js/$file"
          done

      - name: Test Report
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          path: 'ci-report/js/*-xunit-report.xml'
          summary: true
          display-options: a
          fail-on-empty: true
          title: Test results
      - run: nix-shell --run "./scripts/ci-report.sh"
        if: failure() || cancelled()

      - uses: actions/upload-artifact@v7
        if: failure() || cancelled()
        with:
          name: ci-report-int
          path: ./ci-report/ci-report.tar.gz

      - name: Check Coredumps
        if: always()
        run: sudo ./scripts/check-coredumps.sh --since "${TEST_START_DATE}"

      - name: Cleanup
        if: always()
        run: nix-shell --run "./scripts/clean-cargo-tests.sh"
# debugging
      # - name: Setup tmate session
      #   if: ${{ failure() }}
      #   timeout-minutes: 240
      #   uses: mxschmitt/action-tmate@v3
